import js from '@eslint/js';

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        history: 'readonly',
        location: 'readonly',
        BroadcastChannel: 'readonly',
        WebSocket: 'readonly',
        AudioContext: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        FormData: 'readonly',
        HTMLElement: 'readonly',
        HTMLCanvasElement: 'readonly',
        HTMLVideoElement: 'readonly',
        Event: 'readonly',
        MouseEvent: 'readonly',
        PointerEvent: 'readonly',
        KeyboardEvent: 'readonly',
        caches: 'readonly',
        self: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        console: 'readonly',
        crypto: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        process: 'readonly',
        /* Shared flat-scope symbols defined in game.js and used by
           clock.js / share-controller.js in the flattened bundle. */
        S: 'readonly',
        $: 'readonly',
        TICK_PHASES: 'readonly',
        TEAM_HEX: 'readonly',
        TEAM_COLORS: 'readonly',
        countdownTimer: 'writable',
        activeShareTab: 'writable',
        isGuest: 'readonly',
        isHost: 'readonly',
        isSynced: 'readonly',
        show: 'readonly',
        toast: 'readonly',
        renderBoard: 'readonly',
        finishRound: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-undef': 'error',
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'prefer-const': 'warn',
      eqeqeq: 'warn',
    },
  },
  {
    ignores: ['dist/', 'node_modules/', 'sw.js'],
  },
];
