/**
 * words.js - the prompt bank.
 *
 * Two sources of prompts:
 *   1. Curated themes. Hand-picked, tiered 1-3 by how hard they are to draw.
 *   2. Mashups. Composed from parts (adjective x noun x action), which makes
 *      the pool effectively bottomless without padding it with junk.
 *
 * Every prompt here has passed one filter: can somebody actually draw it?
 *
 * All randomness goes through rng.js. Synced multi-device play passes its own
 * generator into mashupWord so two phones derive identical rounds offline.
 */
import { pick } from './rng.js';

const S_ = s => s.split(',');

export const THEMES = [
{id:'animals', name:'Animals', icon:'🐘', words:{
1:S_("dog,cat,elephant,penguin,shark,snail,bee,owl,frog,horse,pig,duck,spider,whale,giraffe,snake,mouse,rabbit,turtle,crab,bat,fox,cow,sheep,parrot,octopus,butterfly,squirrel,camel,jellyfish,peacock,kangaroo,hedgehog,flamingo,lobster,dolphin,tiger,monkey,chicken,goat"),
2:S_("sloth,anteater,chameleon,porcupine,walrus,pelican,armadillo,platypus,meerkat,narwhal,hummingbird,scorpion,starfish,seahorse,woodpecker,tarantula,rhinoceros,orangutan,pufferfish,dragonfly,praying mantis,king cobra,polar bear,sea turtle,stick insect,electric eel,vampire bat,honey badger,hermit crab,flying squirrel,mountain goat,arctic fox,bird of paradise,leafcutter ant,komodo dragon"),
3:S_("cat stuck up a tree,dog chasing its tail,bird feeding chicks in a nest,mouse stealing cheese from a trap,wolf howling at the full moon,bear catching a leaping salmon,monkey stealing sunglasses,penguin sliding on ice,lion jumping through a flaming hoop,frog catching a fly with its tongue,snake charmer playing a flute,beaver building a dam,dog wearing a cone of shame,hamster running on an exercise wheel,squirrel hiding nuts in the ground,bat hanging upside down in a cave,dog eating homework,spider spinning a giant web,cat knocking a glass off a table,swarm of angry bees chasing a bear,flamingo standing on one leg,shark circling a lifeboat,herding sheep into a pen,dinosaur skeleton in a museum,woodpecker drilling a tree trunk,bear raiding a campsite,wildlife safari watching a lion,dog show obstacle course,dolphin jumping through a hoop,owl perched on a pumpkin,pack of wolves in the snow,dog pulling its owner on a leash,horse jumping over a hurdle,chameleon blending into a towel,bull chasing a red cape")}},

{id:'food', name:'Food & Drink', icon:'🍕', words:{
1:S_("pizza,banana,egg,cupcake,sandwich,ice cream,carrot,burger,donut,noodles,watermelon,popcorn,pancakes,cheese,taco,coffee,pretzel,lollipop,corn,soup,sushi,fries,grapes,pineapple,toast,milkshake,hot dog,pie,chilli,olive,apple,bread,rice,cake,tea"),
2:S_("samosa,birthday cake,cotton candy,shaved ice,fondue,dim sum,breakfast in bed,food truck,burnt toast,leftovers,picnic basket,barbecue,ramen bowl,spice rack,rolling pin,cutting board,tea ceremony,street food,buffet,bubble tea,gingerbread house,three course meal,melting ice cream,fortune cookie,hot sauce,mystery meat,soda fountain,candy floss,pressure cooker,jar of pickles"),
3:S_("sneaking cookies from the jar,flipping a pancake onto the ceiling,waiter dropping a giant tray of dishes,food fight in a cafeteria,birthday cake with too many candles,chef tasting soup with a giant spoon,slipping on a banana peel,eating noodles with slippery chopsticks,giant sandwich with twenty layers,hot dog eating contest champion,roasting marshmallows over a campfire,popcorn popping out of an open pot,burning the thanksgiving turkey,brain freeze from drinking a slushie,stealing a french fry from a plate,peeling an onion and crying,breaking open a fortune cookie,gingerbread house collapsing,ice cream scoop falling off the cone,candlelit dinner with spaghetti,bottle of champagne popping its cork,pot of boiling pasta overflowing,midnight snack raid on the fridge,blindfolded taste test,cutting a five tier wedding cake,squeezing ketchup that splatters everywhere,fly floating in a bowl of soup,pie cooling on a windowsill,eating hot chilli with steam from ears,tossing a spinning pizza dough,fondue fountain with dipping strawberries,sweet tooth in a mountain of candy,kitchen nightmare with smoke from oven,cracking an egg with a double yolk,pouring syrup on a stack of pancakes")}},

{id:'house', name:'Around the House', icon:'🛋️', words:{
1:S_("chair,lamp,door,broom,clock,mirror,sock,toothbrush,pillow,kettle,ladder,bucket,hammer,scissors,umbrella,key,candle,fan,rug,shelf,soap,towel,toaster,spoon,vase,blanket,drawer,plug,mop,curtain,window,bed,sofa,fridge,bin"),
2:S_("vacuum cleaner,washing machine,ironing board,fuse box,doorbell,laundry basket,junk drawer,ceiling fan,shoe rack,step stool,fire alarm,sewing kit,tool box,welcome mat,piggy bank,jewellery box,attic,basement,garage sale,houseplant,leaky tap,squeaky door,spring cleaning,moving boxes,bunk bed,fireplace,chandelier,spare room,laundry line,cutlery drawer"),
3:S_("assembling flat pack furniture with an allen key,stepping on a lego brick barefoot,searching for coins under the couch,monster hiding under the bed,sweeping dust under the rug,building a pillow fort in the living room,overflowing bubble bath spilling on floor,changing a lightbulb on a wobbly chair,locked out of the house in the rain,burnt toast setting off the smoke alarm,unblocking a toilet with a plunger,sneaking down the stairs at night,painting the ceiling with a roller,plumbing disaster with water spraying,power cut lighting candles in the dark,searching through a messy attic with cobwebs,dog chewing up a bedroom slipper,cat knocking over a flower pot,hanging a picture frame completely crooked,mountain of dirty laundry spilling over,noisy neighbour playing drums upstairs,untangling a giant ball of cords,robot vacuum cleaner stuck on a rug,hiding inside a wardrobe during hide and seek,looking for lost keys in every drawer,washing a sink full of stacked dishes,ironing a shirt with a scorch mark,watering a wilted houseplant,fixing a squeaking floorboard with a hammer,carrying a heavy sofa up the stairs,trying to fit a mattress through a doorway,cleaning windows with a squeegee,installing a ceiling fan spinning wildly,burning cookies in the oven with smoke,raking a giant pile of leaves in the yard")}},

{id:'nature', name:'Out in Nature', icon:'🌲', words:{
1:S_("tree,cloud,mountain,river,sun,rainbow,cactus,leaf,flower,rock,moon,star,waterfall,beach,snowflake,mushroom,island,volcano,forest,wave,seashell,acorn,fog,lightning,puddle,hill,cave,desert,pond,vine,grass,seed,feather,nest,pebble"),
2:S_("sunrise,tide pool,coral reef,glacier,canyon,swamp,geyser,quicksand,sand dune,hot spring,northern lights,solar eclipse,meteor shower,tornado,hurricane,avalanche,landslide,wildfire,drought,monsoon,tree rings,spider web,anthill,honeycomb,mossy log,shooting star,crescent moon,whirlpool,tidal wave,driftwood"),
3:S_("climbing to the peak of mount everest,camping inside a tent under the stars,erupting volcano spewing orange lava,person sinking slowly in quicksand,message in a bottle on a desert island,white water rafting down rapids,dark cave with stalactites and bats,crossing a rope bridge over a ravine,building a giant snowman in a blizzard,swimming with turtles in a coral reef,uncovering a massive dinosaur fossil,tornado lifting a barn into the sky,ancient shipwreck at the bottom of the sea,watching the northern lights from an igloo,oasis with palm trees in sand dunes,hiking through a thick jungle with a machete,waterfall hiding a secret cave,lightning striking a lone tree in a field,avalanche tumbling down a snowy slope,setting up a tent in howling winds,stargazing through a telescope,polar bear on a melting iceberg,caterpillar in a cocoon turning into butterfly,giant tidal wave crashing on a lighthouse,geyser shooting hot steam into the sky,searching for buried treasure with an x map,wild campfire with sparks flying,walking on the edge of a mountain cliff,jumping into a pile of autumn leaves,getting lost in a foggy pine forest,roasting a fish over an open fire,sunflower turning to follow the sun,swallowed by an ocean whirlpool,bird hatching out of an egg in a nest,frost patterns on a frozen window")}},

{id:'jobs', name:'Jobs & People', icon:'👷', words:{
1:S_("chef,doctor,firefighter,teacher,pilot,farmer,clown,nurse,police officer,artist,barber,mechanic,waiter,builder,dentist,singer,postman,lifeguard,judge,soldier,fisherman,plumber,cleaner,driver,baker,tailor,guard,coach,librarian,gardener,painter,vet,cashier,dancer,magician"),
2:S_("astronaut,archaeologist,detective,stunt double,tattoo artist,air traffic controller,marine biologist,news anchor,sign language interpreter,crash test dummy,street performer,beekeeper,ice sculptor,wedding planner,dog walker,ghost writer,bouncer,auctioneer,tour guide,paramedic,locksmith,cartographer,sommelier,undertaker,welder,glassblower,puppeteer,mime,lighthouse keeper,food taster"),
3:S_("astronaut doing a floating spacewalk,conducting an orchestra with a baton,detective examining fingerprints with magnifying glass,surgeon performing an operation under bright lights,news reporter caught in a windy hurricane,judge banging a wooden gavel in court,stunt double jumping out of a building,window cleaner on a skyscraper platform,magician sawing an assistant in half,circus ringmaster introducing a lion,firefighter rescuing a kitten from a tree,mechanic working underneath a car on a lift,deep sea diver fixing an underwater pipe,bodyguard in sunglasses shielding a vip,barber accidentally shaving off an eyebrow,beekeeper running from a swarm of bees,working from home in pyjamas and a suit,falling asleep on a desk covered in papers,paparazzi chasing a celebrity with cameras,air traffic controller watching radar screens,fashion model tripping on the runway,archaeologist dusting off a golden tomb,teacher writing math on a chalkboard,auctioneer rapidly chanting with a hammer,pizza delivery rider on a scooter in rain,nervous job interview with sweaty palms,office worker racing against a ticking clock,retirement party with cake and balloons,workers marching with protest signs,flight attendant demonstrating an oxygen mask,bank teller facing a masked bank robber,puppeteer pulling strings behind a miniature stage,veterinarian examining a giant growling dog,artist painting a model on an easel,sculptor carving a marble statue with a chisel")}},

{id:'sport', name:'Sports & Games', icon:'⚽', words:{
1:S_("football,basketball,tennis,swimming,cycling,boxing,skiing,surfing,chess,darts,bowling,golf,skateboard,hockey,archery,karate,dancing,yoga,jump rope,kite flying,marbles,frisbee,table tennis,hopscotch,tag,hula hoop,cartwheel,arm wrestling,tug of war,juggling,cricket,running,baseball,badminton,volleyball"),
2:S_("pole vault,high jump,scuba diving,rock climbing,figure skating,synchronised swimming,bungee jumping,paragliding,horse racing,sumo wrestling,fencing,curling,triathlon,rowing,windsurfing,snowboarding,trampoline,gymnastics,rugby scrum,penalty kick,slam dunk,home run,checkmate,poker face,dodgeball,paintball,laser tag,escape room,relay baton,starting blocks"),
3:S_("goalkeeper diving to save a goal,slam dunk shattering the backboard,photo finish with runners diving for the line,standing on top of the podium with a gold medal,referee pulling out a red card,hoisting a shiny championship trophy,knocking down ten bowling pins for a strike,hitting a hole in one on a golf green,boxer knocked out onto the canvas,cyclist crashing over handlebars into a bush,skydiver pulling a parachute ripcord,two sumo wrestlers colliding in a ring,dumping a cooler of gatorade on the coach,figure skater spinning fast on one skate,archer splitting an arrow on a bullseye,stadium crowd doing the wave,tug of war team pulled into a mud pit,skier losing both skis during a jump,bobsleigh team hurtling down an ice track,marathon runner crawling across the finish line,tennis player smashing a racket in frustration,runner dropping the baton during relay handoff,scoring an accidental own goal past the keeper,hitting a bullseye on a dartboard,hockey players dropping gloves for a fight,buzzer beater shot from half court,team mascot doing backflips on the field,pole vaulter soaring over the high bar,baseball batter hit by a pitch,catching a home run ball in a drink cup,surfer riding inside the tube of a giant wave,wrestler jumping off the top turnbuckle,weightlifter lifting a bending heavy barbell,penalty shootout ball hitting the crossbar,swimmer touching the wall ahead by a finger")}},

{id:'travel', name:'Travel & Places', icon:'✈️', words:{
1:S_("airplane,suitcase,map,passport,train,bus,boat,hotel,bridge,tent,taxi,beach,castle,lighthouse,windmill,pyramid,igloo,harbour,tunnel,ferry,backpack,compass,camper van,ticket,street sign,fountain,market,pier,cable car,hot air balloon,road,sign post,anchor,sandcastle,postcard"),
2:S_("layover,baggage claim,duty free,border crossing,road trip,hostel dorm,night train,scenic route,traffic jam,toll booth,rest stop,customs check,cruise ship,safari jeep,mountain pass,ghost town,street market,rooftop bar,ancient ruins,pilgrimage,caravan,houseboat,tree house,capsule hotel,sleeper bus,rickshaw,gondola,funicular,hitchhiking,observation deck"),
3:S_("sprinting through the airport to catch a flight,sitting on top of an overpacked suitcase,lone lost suitcase circling on an empty carousel,tourist posing with the leaning tower of pisa,gondolier singing while steering a gondola,hot air balloon drifting over mountains,sleeping on airport floor during a flight delay,riding a camel past the egyptian pyramids,trying to unfold a giant map in the wind,passport accidentally falling into the ocean,cruise ship sailing past a giant iceberg,hitchhiker holding a cardboard sign,airport security scanner beeping loudly,sleeping in the top bunk of an overnight train,red double decker bus in london traffic,tourist wearing socks with sandals and sunhat,camper van broken down with hissing radiator,climbing the stairs of the eiffel tower,souvenir shop packed with snow globes,passenger getting seasick over ship railing,getting lost inside a giant hedge maze,waking up on train having missed the station,luggage falling off the roof of a bus,checking into a spooky haunted hotel,tuk tuk weaving wildly through night traffic,ordering food abroad using wild hand gestures,border guard stamping a passport firmly,safari tourist dropping camera near a lion,falling asleep on beach with bad sunburn,ziplining across a huge canyon on a cable,sleeping in a hammock between palm trees,riding a horse carriage on cobblestones,taking a selfie on edge of grand canyon,floating boat market with fresh coconuts,scuba diving through a sunken shipwreck")}},

{id:'tech', name:'Tech & Internet', icon:'💻', words:{
1:S_("phone,laptop,headphones,camera,robot,battery,keyboard,mouse,printer,wifi,speaker,charger,drone,satellite,lightbulb,remote,antenna,cable,screen,microchip,joystick,usb stick,smartwatch,router,console,tablet,webcam,hard drive,radio,calculator,plug socket,power button,floppy disk,barcode,password"),
2:S_("video call,screen share,group chat,voice note,face unlock,dark mode,split screen,notification storm,low battery,airplane mode,cloud backup,two factor,browser tabs,autocorrect,typing indicator,read receipt,live stream,green screen,motion capture,self driving car,virtual reality,3d printer,smart fridge,fitness tracker,noise cancelling,wireless charging,solar panel,fingerprint scan,facial recognition,spam folder"),
3:S_("accidentally dropping phone into the toilet,smashing keyboard in rage with both fists,wearing vr headset and walking into a wall,office printer spewing jammed paper and smoke,spilling full cup of coffee on laptop keyboard,talking on a video call while muted,untangling a spaghetti knot of charging cables,taking group photo with a giant selfie stick,robot vacuum cleaner escaping out the front door,smartphone screen shattered into spiderweb cracks,holding phone high in the air hunting for wifi,cat sleeping on a warm laptop keyboard,flying camera drone crashing into a tree,doomscrolling in bed in the dark with glowing face,flipping a usb plug three times to fit,hacker in a black hoodie typing on four screens,pop up ads multiplying and covering the screen,battery dying at one percent before sending text,self driving car confused by a detour sign,3d printer printing a blob of plastic spaghetti,livestreamer knocking over a bright ring light,clickbait thumbnail with open mouth and red arrow,yelling at a smart speaker that does not understand,blowing dust out of an old video game cartridge,tripping over ethernet cable and pulling down pc,robot trying to solve a captcha image test,entering password wrong five times and locked out,accidental reply to all on company wide email,person with fifty open browser tabs on screen,unboxing a new phone and popping bubble wrap,using tablet as giant camera at a concert,smartwatch buzzing with dozens of notifications,download progress bar stuck at ninety nine percent,accidentally turning on goofy face filter on call,rubber duck sitting by monitor for debugging")}},

{id:'feelings', name:'Feelings & Ideas', icon:'💭', words:{
1:S_("love,anger,sleepy,scared,happy,confused,bored,hungry,tired,excited,shy,proud,curious,relieved,panicking,calm,jealous,laughing,crying,surprised,lonely,grateful,nervous,brave,disgusted,hopeful,embarrassed,determined,peaceful,frustrated"),
2:S_("stage fright,homesick,butterflies in the stomach,cold feet,mixed signals,silent treatment,awkward silence,inside joke,pep talk,small talk,white lie,guilt trip,heartbreak,first impression,gut feeling,sixth sense,comfort zone,culture shock,peer pressure,writer's block,second thoughts,road rage,buyer's remorse,eye contact,body language,personal space,false alarm,double take,cold shoulder,pillow talk"),
3:S_("jumping high into the air for joy,sweating nervously hooked up to a lie detector,crying tears of joy clutching a gold trophy,shaking hands with dripping sweaty palms,laughing so hard milk shoots out of nose,staring blankly at a surprise pop quiz test,biting fingernails down to the skin in suspense,screaming at top of lungs on a rollercoaster drop,head exploding with cartoon smoke from confusion,feeling like a tiny goldfish in a sea of sharks,floating on cloud nine with colorful balloons,covering face with hands in extreme embarrassment,seeing a ghost and turning white as a sheet,pulling your own hair out in frustration,bright lightbulb flashing on above head with idea,standing on bow of ship feeling king of the world,turning bright green with envy at a fancy car,daydreaming about a tropical beach while at work,staring up at ceiling at night unable to sleep,jumping out of skin from a sudden jump scare,bursting with pride walking across graduation stage,walking on eggshells around someone furious,trying to hold back laughter in a silent library,sobbing into a box of tissues at a sad movie,blowing a gasket with steam shooting out of ears,struck by cupids love arrow with heart eyes,sitting alone under a personal dark rain cloud,blushing bright red like a tomato after tripping,deer frozen wide eyed in car headlights,pricking a happy balloon with a sharp needle,deja vu seeing the same black cat walk by twice,heart shattering into jagged puzzle pieces,feeling invisible at a crowded loud party,screaming into a soft pillow to vent anger,dancing happily like nobody is watching in room")}},

{id:'actions', name:'Actions', icon:'🤸', words:{
1:S_("running,jumping,sleeping,eating,swimming,dancing,singing,reading,writing,cooking,painting,digging,climbing,falling,pushing,pulling,throwing,catching,kicking,waving,clapping,sneezing,yawning,whistling,shivering,tiptoeing,crawling,hugging,pointing,blowing,sitting,stretching,knocking,sweeping,pouring"),
2:S_("tripping over,tightrope walking,sneaking out,eavesdropping,parallel parking,threading a needle,blowing bubbles,popping balloons,skipping stones,building a sandcastle,changing a tyre,jump starting,wrapping a gift,tying shoelaces,shovelling snow,raking leaves,pitching a tent,hailing a taxi,folding laundry,chasing a bus,slipping on ice,carrying too much,squeezing through,balancing plates,untangling wires,swatting a fly,threading traffic,climbing out a window,catching a falling glass,arm wrestling"),
3:S_("proposing on one knee with a diamond ring,walking a tightrope over snapping crocodiles,juggling three flaming torches in the air,escaping from chains and handcuffs underwater,stepping on a garden rake that hits your nose,chasing a greased pig that keeps slipping away,carrying a tall wobbly stack of ceramic plates,defusing a ticking time bomb by cutting red wire,riding a tall unicycle while playing an accordion,slipping on banana peel and landing in a puddle,digging an escape tunnel under a wall with a spoon,tiptoeing past a sleeping castle guard with keys,jumping out of an airplane and opening parachute,sawing a wooden box in half during magic show,blowing bubble gum that pops all over your face,chasing a runaway stroller down a steep hill,painting yourself into a corner with wet paint,climbing a rope ladder into a rescue helicopter,getting wedged inside a spinning revolving door,untangling a giant knot of christmas fairy lights,trying to milk a stubborn cow that kicks the bucket,balancing a spoon on the tip of your nose,wrestling a giant alligator in a swamp,diving to catch a wedding cake before it drops,running a dash wearing giant scuba flippers,riding a bucking mechanical bull with one hand,leaning forward walking against extreme wind,bouncing off high diving board doing a cannonball,chopping a flying watermelon in half with a kick,swatting a buzzing mosquito on your own forehead,marching in a protest line with cardboard signs,eloping down a wooden ladder from a window,waving a white flag of surrender from a trench,throwing graduation caps high into the air,trying to catch a slippery fish with bare hands")}},

{id:'sayings', name:'Sayings & Idioms', icon:'💬', words:{
1:S_("break the ice,spill the beans,cold feet,piece of cake,hit the sack,under the weather,raining cats and dogs,couch potato,night owl,early bird,bookworm,copycat,daredevil,scaredy cat,chatterbox,lightning fast,snail mail,bear hug,eagle eye,butterfingers,hothead,green thumb,heavy heart,big mouth,open book,tight ship,loose cannon,busy bee,top dog,cash cow"),
2:S_("bite the bullet,burn the midnight oil,cut corners,jump the gun,let the cat out of the bag,beat around the bush,on thin ice,in hot water,over the moon,under the radar,down the rabbit hole,against the clock,back to square one,between a rock and a hard place,a blessing in disguise,the last straw,the tip of the iceberg,the elephant in the room,a wild goose chase,adding fuel to the fire,killing two birds,walking on eggshells,throwing shade,pulling your leg,hitting the nail on the head,missing the boat,riding shotgun,burning bridges,rocking the boat,caught red handed"),
3:S_("bull in a china shop,wolf in sheep's clothing,needle in a haystack,caught with hand in the cookie jar,opening a can of worms,putting all eggs in one basket,too many cooks in the kitchen,grass is always greener on other side,crying over spilt milk,don't count chickens before they hatch,curiosity killed the cat,burning the candle at both ends,head buried in the sand,fish out of water,boy who cried wolf,barking up the wrong tree,skeleton in the closet,storm in a teacup,cat got your tongue,money growing on trees,time flies with wings,once in a blue moon,it takes two to tango,frog in your throat,throwing money out the window,buttering someone up with butter,driving someone up the wall,burying the hatchet in the ground,walking on sunshine,spill the tea,apple of my eye,water under the bridge,bite off more than you can chew,jumping on the bandwagon,leave no stone unturned")}}
];

/* Mashups: composed prompts, effectively bottomless. */
const ADJ = S_("giant,tiny,angry,sleepy,melting,frozen,invisible,upside-down,haunted,glowing,exploding,soggy,ancient,robotic,inflatable,armoured,glittery,rusty,heroic,evil,polite,confused,romantic,burning,floating,underwater,edible,transparent,musical,bulletproof,cursed,royal,pixelated,origami,two-headed,talking,dancing,screaming,microscopic,bouncing,spinning,levitating,camouflaged,knitted,wooden,neon,furry,squeaky,mouldy,time-travelling,electric,golden,slippery,flying,steaming,clumsy,magical,stinky,spiky,feathered,cosmic,fluffy,sneaky,dizzy,hypnotized,radioactive,crystallized,cybernetic,crying,laughing");

const SUBJECT = S_("penguin,wizard,dentist,octopus,pirate,robot,ghost,dragon,astronaut,walrus,grandma,ninja,scarecrow,unicorn,gnome,barber,mummy,hamster,vampire,knight,seagull,werewolf,clown,elephant,mermaid,snowman,detective,parrot,samurai,koala,giraffe,yeti,chef,alien,narwhal,cowboy,flamingo,monk,raccoon,lumberjack,sloth,wrestler,hedgehog,pharaoh,platypus,surfer,goblin,beekeeper,anteater,viking,ferret,camel,juggler,badger,mime,gladiator,moose,barista,toucan,sorcerer,llama,bandit,ostrich,jester,crocodile,puffin,cyclops,armadillo,hitchhiker,gargoyle,dinosaur,t-rex,superhero,monster,kraken,centaur,minotaur,sphinx,pegasus,chimera,gorilla,lemur,panda,iguana,gecko,scuba diver,statue,chimney sweep,deep sea diver,firefighter,doctor,boxer,rockstar,ballerina,queen,king,caveman,pilot,teacher,lifeguard,farmer,scientist,witch,supervillain,acrobat");

const OBJECT = S_("toaster,bicycle,volcano,mailbox,cupcake,traffic cone,vending machine,lighthouse,sock,piano,taxi,burrito,submarine,tornado,jellyfish,skateboard,telescope,chandelier,pineapple,lawnmower,harmonica,igloo,kettle,windmill,accordion,bulldozer,violin,slot machine,tuba,typewriter,carousel,jukebox,trampoline,disco ball,bagpipes,periscope,catapult,zeppelin,xylophone,waffle iron,sundial,harpoon,trebuchet,metronome,hoverboard,blimp,satellite,helicopter,pirate ship,treasure chest,rollercoaster,ferris wheel,bumper car,unicycle,space station,time machine,cannon,guitar,throne,cauldron,sandwich,sword,surfboard,pyramid,boombox,anchor,crown,magic wand,microscope,boomerang");

const NOUN = SUBJECT.concat(OBJECT);

const VERB = S_("riding a bicycle,eating spaghetti,doing yoga,robbing a bank,proposing marriage,taking a selfie,teaching maths,winning a race,losing a hat,fighting a bee,baking a cake,climbing a ladder,playing chess,washing a car,walking a dog,getting a haircut,missing a bus,reading a map,painting a wall,juggling apples,skydiving,ice skating,mowing the lawn,tying shoelaces,blowing bubbles,doing laundry,fixing a pipe,delivering pizza,conducting an orchestra,escaping a cage,stuck in a chimney,waiting in the rain,at the dentist,on a first date,running late,walking on the moon,wrestling an alligator,surfing a tidal wave,riding a rollercoaster,building a sandcastle,defusing a bomb,escaping quicksand,juggling flaming torches,singing karaoke,walking a tightrope,casting a magic spell,flying a kite,driving a racecar,fishing in a puddle,bouncing on a pogo stick,drinking bubble tea,playing electric guitar,hiding from a monster,eating hot chilli,running a marathon,milking a cow,cleaning windows,painting a masterpiece,flipping pancakes,skateboarding down a rail");

/**
 * Which prompt tiers each difficulty draws its three stakes from.
 * Shared by solo card dealing and synced round derivation, which must agree.
 */
export const TIER_LADDER = { easy: [1, 1, 2], medium: [1, 2, 3], hard: [2, 3, 4] };

const MASHUP = {id:'mashup', name:'Mashups', icon:'🎲', gen:true};
export const ALL_THEMES = THEMES.concat([MASHUP]);

/**
 * Compose a prompt from parts.
 * @param {number} tier 1-2 adjective+noun, 3 subject+action, 4 all three
 * @param {{pick:Function}} [rng] isolated generator; synced play passes its own
 *   so the result depends only on the round, not on module-level state
 */
export function mashupWord(tier, rng) {
  const take = rng ? rng.pick : pick;
  if (tier <= 2) return `${take(ADJ)} ${take(NOUN)}`;
  if (tier === 3) return `${take(SUBJECT)} ${take(VERB)}`;
  return `${take(ADJ)} ${take(SUBJECT)} ${take(VERB)}`;
}

/** Count of distinct prompts the bank can produce. */
export function poolSize(){
  let curated = 0;
  THEMES.forEach(t => Object.values(t.words).forEach(l => curated += l.length));
  const m2 = ADJ.length * NOUN.length;
  const m3 = SUBJECT.length * VERB.length;
  const m4 = ADJ.length * SUBJECT.length * VERB.length;
  return {curated, mashup: m2 + m3 + m4, total: curated + m2 + m3 + m4};
}
